### ISSUE TITLE
Access to google cloud storage denied

### ISSUE THREAD

**Issue by SchmiediGonzales440** [kylemcdonald/ethereum-emissions#6]
Trying to download the snapshot of Ethereum blockchain metadata but I receive this message: 

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details>
</Error>

**Comment by kylemcdonald** [comment]
Thanks, fixed it. I had the allUsers permissions configured to "Bucket reader" instead of "Object reader".
